---
title: "Comparing individual and consensus"
output: html_document
---

```{r libraries}
library(tidyverse)
library(WGCNA)
```

```{r}
##Load in Data for consensus and ovary modules
cons_names<-load("../data/ConsensusModules_BvsFBO.RData")
ova_names<-load("../data/OvaryModules.RData")

# Labels are ovaryMLabels, consMLabels
#Colors are ovaryMColors, consMColors
#trees are ovaryTree, consTree
#MEs are ovaryMEs, consMEs


##module labels 
ovaModuleLabels = substring(names(ovaryMEs[[1]]$data), 3)
consModuleLabels = substring(names(consMEs[[1]]$data), 3)



#can also convert numeric labels to colors using labels2colors(as.numeric())
ovaModules = ovaryMLabels

consModules =consMLabels

# Numbers of female and consensus modules
nOvaMods = length(ovaModuleLabels)
nConsMods = length(consModuleLabels)

## Initialize tables of p-values and of the corresponding counts
pTable = matrix(0, nrow = nOvaMods, ncol = nConsMods)
CountTbl = matrix(0, nrow = nOvaMods, ncol = nConsMods)

# Execute all pairwaise comparisons
for (omod in 1:nOvaMods)
  for (cmod in 1:nConsMods)
  {

    ovaMembers = (ovaryMLabels == ovaryMLabels[omod]);
    consMembers = (consMLabels == consMLabels[cmod]);
    pTable[omod, cmod] = -log10(fisher.test(ovaMembers, consMembers, alternative = "greater")$p.value);
    CountTbl[omod, cmod] = sum(ovaryMLabels == ovaModules[omod] & consMLabels ==
                      consModules[cmod])

  }

# Truncate p values smaller than 10^{-50} to 10^{-50} 
pTable[is.infinite(pTable)] = 1.3*max(pTable[is.finite(pTable)]);
pTable[pTable>50 ] = 50 ;
# Marginal counts (really module sizes)
ovaModTotals = apply(CountTbl, 1, sum)
consModTotals = apply(CountTbl, 2, sum)
# Actual plotting
sizeGrWindow(10,7 );
pdf(file = "../figures/ConsensusVsovaryModules.pdf", wi = 20, he = 20);
par(mfrow=c(1,1));
par(cex = 1.0);
par(mar=c(8, 10.4, 2.7, 1)+0.3);
# Use function labeledHeatmap to produce the color-coded table with all the trimmings
labeledHeatmap(Matrix = pTable,
               xLabels = paste(" ", consModuleLabels),
               yLabels = paste(" ", ovaModuleLabels),
               colorLabels = F,
               xSymbols = paste("Cons ", consModuleLabels, ": ", consModTotals, sep=""),
               ySymbols = paste("Fem ", ovaModuleLabels, ": ", ovaModTotals, sep=""),
               textMatrix = CountTbl,
               colors = greenWhiteRed(100)[50:100],
               main = "Correspondence of ovary set-specific and brain-ovary consensus modules",
               cex.text = 1.0, cex.lab = 1.0, setStdMargins = FALSE);
dev.off();


```